apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi
  template:
    metadata:
      labels:
        app: mi
    spec:
      containers:
        - name: mi
          image: hesxo/mi-config:9
          imagePullPolicy: Always
          ports:
            - containerPort: 8290
